server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance-app
    username: root
    password: aditya(2003)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: "user-consumer-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.user_consumer.user_consumer.deserializer.UserConsumerDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: user:user_consumer.user_consumer.entities.User


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka