server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance-app
    username: root
    password: aditya(2003)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.user_service.serializer.UserSerializer
      properties:
        spring.json.type.mapping: "user:com.user_service.entities.User"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka