server:
  port: 7076

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: adityabedi3000@gmail.com
    password: your-password-from-gmail-app-password-setting
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/finance-app
    username: root
    password: aditya(2003)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

    consumer-groups:
      budget-alert-group:
        group-id: "budget-alert-group"
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: com.message_service.deserializer.BudgetDeserializer
        properties:
          spring.json.type.mapping: budget:message_service.entities.Budget
          spring.json.trusted.packages: "*"
      goal-alert-group:
        group-id: "goal-alert-group"
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: com.message_service.deserializer.GoalDeserializer
        properties:
          spring.json.type.mapping: goal:message_service.entities.Goal
          spring.json.trusted.packages: "*"
      transaction-event-group:
        group-id: "transaction-message-group"
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: com.message_service.deserializer.TransactionDeserializer
        properties:
          spring.json.type.mapping: transaction:message_service.entities.Transaction
          spring.json.trusted.packages: "*"
      user-event-group:
        group-id: "user-message-group"
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: com.message_service.deserializer.UserDeserializer
        properties:
          spring.json.type.mapping: user:message_service.entities.User
          spring.json.trusted.packages: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka