server:
  port: 7073

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance-app
    username: root
    password: aditya(2003)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.budget_service.serializer.BudgetSerializer
      properties:
        spring.json.type.mapping: "budget:com.budget_service.entities.Budget"
    consumer:
      auto-offset-reset: earliest
      group-id: "transaction-consumer-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.budget_service.deserializer.BudgetDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: transaction:budget_service.entities.Transaction

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka